# Generated by Django 5.0.9 on 2026-08-20 04:09

import apps.accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Ism')),
                ('code', models.CharField(db_index=True, max_length=8, verbose_name='Kod')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'Telegram kirish kodi',
                'verbose_name_plural': 'Telegram kirish kodlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name="Ko'rinadigan ism")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2, verbose_name='CEFR daraja')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unknown', "Ko'rsatilmagan")], default='unknown', max_length=10, verbose_name='Jins')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English')], default='uz', max_length=2, verbose_name='Interfeys tili')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Ketma-ket kunlar')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Tugatilgan darslar')),
                ('translations_contributed', models.PositiveIntegerField(default=0, verbose_name="Qo'shgan tarjimalar")),
                ('invite_code', models.CharField(db_index=True, default=apps.accounts.models.generate_invite_code, max_length=12, unique=True, verbose_name='Taklif kodi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='Kim taklif qilgan')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Soniya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik faollik',
                'verbose_name_plural': 'Kunlik faollik',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
