# Generated by Django 5.0.9 on 2026-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lessons_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='translations_contributed',
        ),
    ]
