# Generated by Django 5.0.9 on 2026-09-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_lessons_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAccountLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Qurilma / brauzer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test akkaunt kirishi',
                'verbose_name_plural': 'Test akkaunt kirishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
