# Generated by Django 5.0.9 on 2026-09-02 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testaccountlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('platform', models.CharField(max_length=12, verbose_name='Platforma')),
                ('sid', models.CharField(max_length=64, verbose_name='Sessiya ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faol sessiya',
                'verbose_name_plural': 'Faol sessiyalar',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
