# Generated by Django 5.0.9 on 2026-09-02 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='device',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qurilma / brauzer'),
        ),
        migrations.AddField(
            model_name='activesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AddField(
            model_name='activesession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi so'rov"),
        ),
        migrations.CreateModel(
            name='PendingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram chat ID')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to=settings.AUTH_USER_MODEL, verbose_name='Kim taklif qilgan')),
            ],
            options={
                'verbose_name': 'Kutilayotgan taklif',
                'verbose_name_plural': 'Kutilayotgan takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('source', models.CharField(choices=[('bot', 'Bot havolasi'), ('setup', "Ro'yxatdan o'tishda kod")], default='bot', max_length=12, verbose_name='Manba')),
                ('notified', models.BooleanField(default=False, verbose_name='Taklif qilganga xabar berildi')),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_record', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilingan')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilgan')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inviter', 'created_at'], name='accounts_in_inviter_fbf9fc_idx')],
            },
        ),
    ]
