# Generated by Django 5.0.9 on 2026-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activesession_device_activesession_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="O'chirish so'rovi"),
        ),
    ]
