# Generated by Django 5.0.9 on 2026-08-20 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Kod')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Nomi (uz)')),
                ('name_en', models.CharField(max_length=80, verbose_name='Nomi (en)')),
                ('price_uzs', models.PositiveIntegerField(default=0, verbose_name="Narx (so'm/oy)")),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Narx ($/oy)')),
                ('features_uz', models.JSONField(blank=True, default=list, verbose_name='Imkoniyatlar (uz)')),
                ('features_en', models.JSONField(blank=True, default=list, verbose_name='Imkoniyatlar (en)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart (yangi foydalanuvchiga)')),
                ('daily_lesson_limit', models.PositiveIntegerField(default=0, verbose_name='Kunlik dars limiti (0 = cheksiz)')),
                ('daily_exam_limit', models.PositiveIntegerField(default=0, verbose_name='Kunlik test limiti (0 = cheksiz)')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('provider', models.CharField(choices=[('click', 'Click'), ('manual', "Qo'lda")], default='manual', max_length=12, verbose_name='Provayder')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Xatolik')], default='pending', max_length=12, verbose_name='Holat')),
                ('amount_uzs', models.PositiveIntegerField(default=0, verbose_name="Summa (so'm)")),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='Tashqi ID')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name="Xom ma'lumot")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=12, verbose_name='Holat')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugaydi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-started_at'],
            },
        ),
    ]
