# Generated by Django 5.0.9 on 2026-09-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='daily_dictation_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name="Kunlik Diktant (bo'sh = cheksiz)"),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_ielts_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name="Kunlik IELTS test (bo'sh = cheksiz)"),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_shorts_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name="Kunlik Shorts (bo'sh = cheksiz)"),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_video_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name="Kunlik Video (bo'sh = cheksiz)"),
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('kind', models.CharField(max_length=16, verbose_name='Tur')),
                ('ref', models.CharField(max_length=64, verbose_name='Kontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik ishlatilish',
                'verbose_name_plural': 'Kunlik ishlatilish',
                'indexes': [models.Index(fields=['user', 'date', 'kind'], name='billing_dai_user_id_4b75d7_idx')],
                'unique_together': {('user', 'date', 'kind', 'ref')},
            },
        ),
    ]
