# Generated by Django 5.0.9 on 2026-09-02 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def dedupe_subscriptions(apps, schema_editor):
    """Bitta foydalanuvchida bir nechta obuna qolgan bo'lsa — eng yangisini qoldiramiz.

    `Subscription` endi FAQAT joriy tarifni saqlaydi (tarix `SubscriptionEvent`
    da), shu bois unique constraint qo'yiladi. Eski bazada dubl bo'lsa
    migratsiya yiqilmasin.
    """
    Subscription = apps.get_model("billing", "Subscription")
    seen = set()
    for sub in Subscription.objects.order_by("user_id", "-started_at", "-id"):
        if sub.user_id in seen:
            sub.delete()
        else:
            seen.add(sub.user_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_daily_dictation_limit_plan_daily_ielts_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('months', models.PositiveIntegerField(default=1, verbose_name='Necha oy')),
                ('invites_spent', models.PositiveIntegerField(verbose_name='Sarflangan taklif')),
            ],
            options={
                'verbose_name': "Taklif sovg'asi",
                'verbose_name_plural': "Taklif sovg'alari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(choices=[('paid', "To'lov"), ('invite', "Do'st taklif qilgani uchun"), ('manual', "Admin qo'lda bergan"), ('test', 'Test akkaunt'), ('free', 'Bepul tarif')], default='manual', max_length=12, verbose_name='Sababi')),
                ('months', models.PositiveIntegerField(default=0, help_text="0 = muddatsiz yoki noma'lum.", verbose_name='Necha oyga')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugaydi')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Tarif tarixi',
                'verbose_name_plural': 'Tarif tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='reason',
            field=models.CharField(choices=[('paid', "To'lov"), ('invite', "Do'st taklif qilgani uchun"), ('manual', "Admin qo'lda bergan"), ('test', 'Test akkaunt'), ('free', 'Bepul tarif')], default='manual', help_text="Tarif qanday olingan: to'lov, taklif, admin yoki test.", max_length=12, verbose_name='Sababi'),
        ),
        migrations.RunPython(dedupe_subscriptions, noop),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_current_subscription'),
        ),
        migrations.AddField(
            model_name='invitereward',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_rewards', to='billing.plan', verbose_name='Berilgan tarif'),
        ),
        migrations.AddField(
            model_name='invitereward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.plan', verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='invitereward',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_rewards', to='billing.subscriptionevent', verbose_name='Tarix yozuvi'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['user', '-created_at'], name='billing_sub_user_id_c9a401_idx'),
        ),
    ]
