# Generated by Django 5.0.9 on 2026-08-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat ID')),
                ('kind', models.CharField(choices=[('reminder', 'Eslatma'), ('streak', 'Streak'), ('broadcast', 'Ommaviy xabar'), ('system', 'Tizim')], default='system', max_length=12, verbose_name='Turi')),
                ('text', models.TextField(verbose_name='Matn')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborilgan'), ('failed', 'Xatolik')], db_index=True, default='pending', max_length=10, verbose_name='Holat')),
                ('error', models.TextField(blank=True, verbose_name='Xatolik')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_messages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bot xabari',
                'verbose_name_plural': 'Bot xabarlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
