# Generated by Django 5.0.9 on 2026-08-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('contact_telegram', models.CharField(blank=True, default='', help_text="@ SIZ ye — faqat username. Masalan: sodiq2005 → t.me/sodiq2005. Bo'sh qoldirilsa 'Bog'lanish' menyusi ko'rinmaydi.", max_length=64, verbose_name="Bog'lanish uchun Telegram username")),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
