# Generated by Django 5.0.9 on 2026-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_active', models.BooleanField(default=False, help_text="Yoqilsa ilova ochilganda shu reklama chiqadi. Bir vaqtda eng oxirgi faol reklama ko'rsatiladi.", verbose_name='Faol')),
                ('image', models.ImageField(blank=True, help_text="PNG / JPG / GIF. Modal tepasida ko'rsatiladi.", null=True, upload_to='ads/', verbose_name='Rasm yoki GIF')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, default='', help_text="Ixtiyoriy. Ichidagi havolalar (https://...) ilovada bosiladigan bo'ladi.", verbose_name='Matn')),
                ('link_url', models.URLField(blank=True, default='', help_text="Bo'sh bo'lmasa — rasm/tugma bosilганда shu havola ochiladi.", verbose_name='Bosilganda ochiladigan havola')),
                ('duration_sec', models.PositiveIntegerField(default=0, help_text='0 — foydalanuvchi X ni bosmaguncha turadi. Masalan 5 — 5 soniyadan keyin yopiladi.', verbose_name='Avto-yopilish (soniya)')),
            ],
            options={
                'verbose_name': 'Ilova reklamasi',
                'verbose_name_plural': 'Ilova reklamalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
