# Generated by Django 5.0.9 on 2026-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_appad'),
    ]

    operations = [
        migrations.AddField(
            model_name='appad',
            name='image_web',
            field=models.ImageField(blank=True, help_text="PNG / JPG / GIF. Saytdagi modal uchun — odatda kengroq (landshaft) rasm. Bo'sh qoldirilsa mobil rasm ishlatiladi.", null=True, upload_to='ads/', verbose_name='Rasm yoki GIF — SAYT'),
        ),
        migrations.AlterField(
            model_name='appad',
            name='image',
            field=models.ImageField(blank=True, help_text="PNG / JPG / GIF. Ilovadagi modal tepasida ko'rsatiladi. Odatda tik (portret) rasm.", null=True, upload_to='ads/', verbose_name='Rasm yoki GIF — MOBIL'),
        ),
    ]
