# Generated by Django 5.0.9 on 2026-09-09 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('months', models.PositiveSmallIntegerField(default=1, verbose_name='Necha oyga')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('input', 'Yaratildi'), ('waiting', "To'lov jarayonda"), ('confirmed', "To'landi"), ('rejected', 'Bekor qilindi')], db_index=True, default='input', max_length=12, verbose_name='Holat')),
                ('status_note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('click_trans_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Click tranzaksiya ID')),
                ('click_paydoc_id', models.BigIntegerField(blank=True, null=True, verbose_name="Click to'lov hujjati")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan")),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_orders', to='billing.plan', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Click buyurtmasi',
                'verbose_name_plural': 'Click buyurtmalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='click_click_user_id_610ae3_idx')],
            },
        ),
    ]
