# Generated by Django 5.0.9 on 2026-09-09 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaynetCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('password_hash', models.CharField(max_length=256, verbose_name='Parol (hash)')),
            ],
            options={
                'verbose_name': 'Paynet paroli',
                'verbose_name_plural': 'Paynet paroli',
            },
        ),
        migrations.CreateModel(
            name='PaynetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('transaction_id', models.BigIntegerField(db_index=True, help_text='Paynet tomonidan berilgan `transactionId`.', unique=True, verbose_name='Paynet tranzaksiya ID')),
                ('service_id', models.IntegerField(db_index=True, verbose_name='Servis ID')),
                ('amount_tiyin', models.BigIntegerField(verbose_name='Summa (tiyin)')),
                ('state', models.SmallIntegerField(choices=[(1, 'Muvaffaqiyatli'), (2, 'Bekor qilingan'), (3, 'Topilmadi')], db_index=True, default=1, verbose_name='Holat')),
                ('fields', models.JSONField(blank=True, default=dict, verbose_name='Paynet yuborgan maydonlar')),
                ('performed_at', models.DateTimeField(db_index=True, verbose_name="O'tkazilgan")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paynet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Paynet tranzaksiyasi',
                'verbose_name_plural': 'Paynet tranzaksiyalari',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['service_id', 'state', 'performed_at'], name='paynet_payn_service_971951_idx')],
            },
        ),
    ]
