# Generated by Django 5.0.9 on 2026-08-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, help_text="Bo'sh qoldirilsa sarlavhadan avtomatik yaratiladi.", max_length=280, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('short_story', 'Short Stories'), ('conversation', 'Suhbatlar'), ('number', 'Raqamlar'), ('spelling', 'Ismlarni harflab yozish'), ('ielts', 'IELTS Listening'), ('toefl', 'TOEFL Listening'), ('toeic', 'TOEIC Listening'), ('news', 'Yangiliklar'), ('random_video', 'Tasodifiy videolar'), ('ted', 'TED'), ('kids_story', 'Bolalar uchun hikoyalar'), ('medical', 'Tibbiy ingliz tili'), ('ipa', 'IPA (talaffuz)')], db_index=True, help_text="Sayt navigatsiyasida shu bo'yicha guruhlanadi.", max_length=20, verbose_name='Mavzu')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='B1', max_length=2, verbose_name='Daraja')),
                ('audio', models.FileField(blank=True, help_text="mp3 / wav. Diktant asosan shu audio bo'yicha yoziladi.", null=True, upload_to='dictations/audio/%Y/%m/', verbose_name='Audio fayl')),
                ('is_media', models.BooleanField(db_index=True, default=False, help_text="Belgilansa YouTube havolasi qo'shiladi va frontendda ko'rsatiladi.", verbose_name='Video ham bor?')),
                ('youtube_link', models.URLField(blank=True, help_text="Faqat 'Video ham bor?' belgilangan diktantlar uchun.", verbose_name='YouTube havolasi')),
                ('body', models.JSONField(blank=True, default=list, help_text='[{"start_ms": 0, "end_ms": 3800, "text": "Hello there."}, ...]', verbose_name='Transkript (timestamp bilan)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Chop etilgan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('practiced_time', models.PositiveBigIntegerField(default=0, help_text='Barcha foydalanuvchilar tomonidan diktant ustida sarflangan vaqt.', verbose_name='Umumiy tinglagan vaqt (ms)')),
            ],
            options={
                'verbose_name': 'Diktant',
                'verbose_name_plural': 'Diktantlar',
                'ordering': ['type', '-created_at'],
                'indexes': [models.Index(fields=['type', 'is_published'], name='catalog_dic_type_080dca_idx'), models.Index(fields=['cefr_level', 'is_published'], name='catalog_dic_cefr_le_d97e25_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Foiz')),
                ('last_index', models.PositiveIntegerField(default=0, verbose_name='Oxirgi chunk')),
                ('draft_answers', models.JSONField(blank=True, default=dict, verbose_name='Saqlangan javoblar')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan')),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='catalog.dictation', verbose_name='Diktant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Diktant progressi',
                'verbose_name_plural': 'Diktant progresslari',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'dictation')},
            },
        ),
    ]
