# Generated by Django 5.0.9 on 2026-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='audio_duration_sec',
            field=models.PositiveIntegerField(default=0, help_text="Faylni yuklaganda avtomatik o'lchanadi.", verbose_name='Audio davomiyligi (soniya)'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='full_text',
            field=models.TextField(blank=True, default='', help_text="Whisper'ning to'liq matni. Katta hajmga tayyor.", verbose_name="To'liq matn (formatlanmagan)"),
        ),
        migrations.AddField(
            model_name='dictation',
            name='transcription_error',
            field=models.TextField(blank=True, default='', help_text="AI to'ldirish urinishida yuz bergan xato (agar bor bo'lsa).", verbose_name='Oxirgi xato'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='transcription_status',
            field=models.CharField(choices=[('idle', "Bo'sh"), ('processing', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='idle', max_length=12, verbose_name='Transkript holati'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='words_json',
            field=models.JSONField(blank=True, default=list, help_text='[{"start": 0.12, "end": 0.48, "word": "Hello"}, ...] — so\'z-so\'z ijro/tekshiruv uchun.', verbose_name="So'z darajasidagi timestamp"),
        ),
        migrations.AddIndex(
            model_name='dictation',
            index=models.Index(fields=['transcription_status'], name='catalog_dic_transcr_970828_idx'),
        ),
    ]
