# Generated by Django 5.0.9 on 2026-08-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dictation_audio_duration_sec_dictation_full_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationDictation',
            fields=[
            ],
            options={
                'verbose_name': '2. Suhbat',
                'verbose_name_plural': '2. Suhbatlar (Conversations)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='IeltsDictation',
            fields=[
            ],
            options={
                'verbose_name': '4. IELTS Listening',
                'verbose_name_plural': '4. IELTS Listening',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='NewsDictation',
            fields=[
            ],
            options={
                'verbose_name': '6. Yangilik (video)',
                'verbose_name_plural': '6. News (video)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='NumberDictation',
            fields=[
            ],
            options={
                'verbose_name': '8. Raqamlar',
                'verbose_name_plural': '8. Numbers',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='RandomVideoDictation',
            fields=[
            ],
            options={
                'verbose_name': '5. Tasodifiy video',
                'verbose_name_plural': '5. Random Videos (video)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='ShortStoryDictation',
            fields=[
            ],
            options={
                'verbose_name': '1. Short Story',
                'verbose_name_plural': '1. Short Stories',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='SpellingDictation',
            fields=[
            ],
            options={
                'verbose_name': '9. Harflab yozish',
                'verbose_name_plural': '9. Spelling Names',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='ToeflDictation',
            fields=[
            ],
            options={
                'verbose_name': '7. TOEFL Listening',
                'verbose_name_plural': '7. TOEFL Listening',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='ToeicDictation',
            fields=[
            ],
            options={
                'verbose_name': '3. TOEIC Listening',
                'verbose_name_plural': '3. TOEIC Listening',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
    ]
