# Generated by Django 5.0.9 on 2026-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_conversationdictation_ieltsdictation_newsdictation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='', help_text="Bo'sh qoldirilsa AI transkript matnini tahlil qilib avtomatik aniqlaydi. Qo'lda tahrirlash mumkin.", max_length=2, verbose_name='Daraja'),
        ),
    ]
