# Generated by Django 5.0.9 on 2026-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_dictation_cefr_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('youtube_link', models.URLField(help_text="YouTube Shorts URL (masalan: https://youtube.com/shorts/XXXXXXXXXXX). Qolgani AI orqali avtomatik to'ldiriladi.", unique=True, verbose_name='YouTube havolasi')),
                ('youtube_id', models.CharField(blank=True, db_index=True, default='', help_text="URL'dan avtomatik ajratiladi.", max_length=16, verbose_name='YouTube ID (avto)')),
                ('title', models.CharField(blank=True, default='', help_text="AI to'ldirsa YouTube video sarlavhasi olinadi.", max_length=250, verbose_name='Sarlavha (avto)')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='Davomiylik (soniya)')),
                ('full_text', models.TextField(blank=True, default='', help_text="Whisper natijasi — timestamp'lar bilan formatlangan.", verbose_name="To'liq transkript")),
                ('words_json', models.JSONField(blank=True, default=list, help_text='[{"start": 0.12, "end": 0.48, "word": "Hello"}, ...]', verbose_name="So'z darajasidagi timestamp")),
                ('cefr_from', models.CharField(blank=True, default='', max_length=2, verbose_name='CEFR (min)')),
                ('cefr_to', models.CharField(blank=True, default='', max_length=2, verbose_name='CEFR (max)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='AI aniqlagan 10 ta mavzu tegi.', verbose_name='Teglar (10 ta)')),
                ('mcq_questions', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "options": {"A": "...", "B": "...", "C": "...", "D": "..."}, "answer": "A", "proof_from_text": "[12.3] iqtibos"}, ...]', verbose_name='Multiple choice savollar')),
                ('tfng_questions', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "True"|"False"|"Not given", "proof_from_text": "[12.3] iqtibos"}, ...]', verbose_name='True/False/Not given savollar')),
                ('transcription_status', models.CharField(choices=[('idle', "Bo'sh"), ('processing', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='idle', max_length=12, verbose_name='AI holati')),
                ('transcription_error', models.TextField(blank=True, default='', verbose_name='Oxirgi xato')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Chop etilgan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='catalog_sho_is_publ_3afa15_idx')],
            },
        ),
    ]
