# Generated by Django 5.0.9 on 2026-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name="Dislike'lar"),
        ),
        migrations.AddField(
            model_name='short',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name="Like'lar"),
        ),
    ]
