# Generated by Django 5.0.9 on 2026-08-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_short_dislikes_short_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortQuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('text', models.TextField(help_text='Foydalanuvchi qaysi savol qanday xato ekanligini yozadi.', verbose_name='Feedback matni')),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to='catalog.short', verbose_name='Short')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_question_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savol xatolik haqida',
                'verbose_name_plural': 'Savol xatolik xabarlari',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'short')},
            },
        ),
        migrations.CreateModel(
            name='ShortReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(choices=[('sexual', 'Jinsiy kontent'), ('violent', "Zo'ravonlik / xavfli harakat"), ('hate', 'Nafrat / haqorat'), ('harassment', "Ta'qib / bezovtalash"), ('misinfo', "Yolg'on / noto'g'ri ma'lumot"), ('spam', 'Spam / firibgarlik'), ('child_safety', 'Bolalar xavfsizligi'), ('other', 'Boshqa')], max_length=20, verbose_name='Sabab')),
                ('text', models.TextField(blank=True, default='', help_text="Ixtiyoriy — user shikoyatga sharh qo'shishi mumkin.", verbose_name="Qo'shimcha izoh")),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.short', verbose_name='Short')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_reports', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Short shikoyati',
                'verbose_name_plural': 'Short shikoyatlari',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'short')},
            },
        ),
    ]
