# Generated by Django 5.0.9 on 2026-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_shortquestionfeedback_shortreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='content_type',
            field=models.CharField(choices=[('short', 'Short (qisqa)'), ('news', 'Yangilik'), ('cartoon', 'Multfilm'), ('movie', 'Film / uzun video')], db_index=True, default='short', max_length=10, verbose_name='Kontent turi'),
        ),
        migrations.AddField(
            model_name='short',
            name='fill_gap_questions',
            field=models.JSONField(blank=True, default=list, help_text='[{"sentence": "He wants to ___ home.", "answer": "call", "proof_from_text": "[3.4] iqtibos"}, ...]', verbose_name="Bo'shliqni to'ldirish savollari"),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['content_type', 'is_published'], name='catalog_sho_content_0e0f1c_idx'),
        ),
    ]
