# Generated by Django 5.0.9 on 2026-08-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_short_content_type_short_fill_gap_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='dead_report_count',
            field=models.PositiveIntegerField(default=0, verbose_name="'O'lik' xabarlar soni"),
        ),
        migrations.AddField(
            model_name='short',
            name='dead_reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi 'o'lik' xabari"),
        ),
        migrations.AddField(
            model_name='short',
            name='is_dead',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Video o'lik (YouTube'da yo'q)"),
        ),
    ]
