# Generated by Django 5.0.9 on 2026-08-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_short_dead_report_count_short_dead_reported_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadVideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('youtube_url', models.URLField(verbose_name='YouTube havolasi')),
                ('youtube_id', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='YouTube ID')),
                ('verified', models.BooleanField(db_index=True, default=False, help_text="Server oEmbed orqali videoning haqiqatan yo'qligini tasdiqladimi.", verbose_name='Server tasdiqladi')),
                ('verify_result', models.CharField(choices=[('unknown', 'Tekshirilmagan'), ('alive', 'Tekshirildi — mavjud'), ('dead', "Tekshirildi — yo'q"), ('error', "Tekshirib bo'lmadi")], default='unknown', max_length=10, verbose_name='Tekshiruv natijasi')),
                ('verify_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='Tekshiruv izohi')),
                ('dictation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_reports', to='catalog.dictation', verbose_name='Manba Diktant')),
                ('short', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_reports', to='catalog.short', verbose_name='Manba Short')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_video_reports', to=settings.AUTH_USER_MODEL, verbose_name='Xabarchi')),
            ],
            options={
                'verbose_name': "O'lik video xabari",
                'verbose_name_plural': "O'lik video xabarlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verified', '-created_at'], name='catalog_dea_verifie_39a683_idx')],
            },
        ),
    ]
