# Generated by Django 5.0.9 on 2026-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_deadvideoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='fill_gap_questions',
            field=models.JSONField(blank=True, default=list, verbose_name="Bo'shliqni to'ldirish savollari (AI)"),
        ),
        migrations.AddField(
            model_name='dictation',
            name='mcq_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='MCQ savollar (AI)'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='tests_error',
            field=models.TextField(blank=True, default='', verbose_name='Test yaratishdagi xato'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='tests_status',
            field=models.CharField(choices=[('idle', "Bo'sh"), ('processing', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], default='idle', max_length=12, verbose_name='Test AI holati'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='tfng_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='TFNG savollar (AI)'),
        ),
    ]
