# Generated by Django 5.0.9 on 2026-08-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_dictation_fill_gap_questions_dictation_mcq_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('kind', models.CharField(choices=[('short', 'Short'), ('dictation', 'Dictation')], db_index=True, max_length=12, verbose_name='Turi')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='Obyekt ID')),
                ('step', models.CharField(choices=[('whisper', 'Whisper (transkript)'), ('haiku', 'Haiku (savollar)')], max_length=10, verbose_name='Bosqich')),
                ('status', models.CharField(choices=[('pending', 'Kutayapti'), ('running', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='pending', max_length=8, verbose_name='Holat')),
                ('error', models.TextField(blank=True, default='', verbose_name='Xato matni')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Urinishlar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlandi')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugadi')),
            ],
            options={
                'verbose_name': 'AI ish',
                'verbose_name_plural': 'AI ish navbati',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='catalog_aij_status_02eb3a_idx'), models.Index(fields=['kind', 'object_id', 'step'], name='catalog_aij_kind_09bec1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aijob',
            constraint=models.UniqueConstraint(fields=('kind', 'object_id', 'step'), name='uniq_ai_job_per_step'),
        ),
    ]
