# Generated by Django 5.0.9 on 2026-08-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_aijob_aijob_uniq_ai_job_per_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationQuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('text', models.TextField(help_text='Foydalanuvchi qaysi savol qanday xato ekanligini yozadi.', verbose_name='Feedback matni')),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to='catalog.dictation', verbose_name='Diktant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_question_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Diktant savol xatoligi',
                'verbose_name_plural': 'Diktant savol xatoliklari',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'dictation')},
            },
        ),
        migrations.CreateModel(
            name='DictationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(choices=[('sexual', 'Jinsiy kontent'), ('violent', "Zo'ravonlik / xavfli harakat"), ('hate', 'Nafrat / haqorat'), ('harassment', "Ta'qib / bezovtalash"), ('misinfo', "Yolg'on / noto'g'ri ma'lumot"), ('spam', 'Spam / firibgarlik'), ('child_safety', 'Bolalar xavfsizligi'), ('other', 'Boshqa')], max_length=20, verbose_name='Sabab')),
                ('text', models.TextField(blank=True, default='', help_text="Ixtiyoriy — user shikoyatga sharh qo'shishi mumkin.", verbose_name="Qo'shimcha izoh")),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='catalog.dictation', verbose_name='Diktant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_reports', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Diktant shikoyati',
                'verbose_name_plural': 'Diktant shikoyatlari',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'dictation')},
            },
        ),
    ]
