# Generated by Django 5.0.9 on 2026-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_dictationquestionfeedback_dictationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='type',
            field=models.CharField(choices=[('short_story', 'Short Stories'), ('conversation', 'Suhbatlar'), ('number', 'Raqamlar'), ('spelling', 'Ismlarni harflab yozish'), ('ielts', 'IELTS Listening'), ('toefl', 'TOEFL Listening'), ('toeic', 'TOEIC Listening'), ('news', 'Yangiliklar'), ('random_video', 'Tasodifiy videolar'), ('ted', 'TED'), ('kids_story', 'Bolalar uchun hikoyalar')], db_index=True, help_text="Sayt navigatsiyasida shu bo'yicha guruhlanadi.", max_length=20, verbose_name='Mavzu'),
        ),
    ]
