# Generated by Django 5.0.9 on 2026-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_dictation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text="0 = oddiy. Katta raqam = lentada oldinroq chiqadi (10 gacha). Bir xil raqamlilar o'zaro tasodifiy tartibda.", verbose_name='Ustuvorlik'),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['-priority', '-created_at'], name='catalog_sho_priorit_6bf753_idx'),
        ),
    ]
