# Generated by Django 5.0.9 on 2026-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_short_priority_short_catalog_sho_priorit_6bf753_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='kind',
            field=models.CharField(choices=[('short', 'Short'), ('dictation', 'Dictation'), ('channel', 'Kanal ingest')], db_index=True, max_length=12, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='step',
            field=models.CharField(choices=[('whisper', 'Whisper (transkript)'), ('haiku', 'Haiku (savollar)'), ('ingest', "Kanaldan yig'ish")], max_length=10, verbose_name='Bosqich'),
        ),
        migrations.CreateModel(
            name='ChannelIngestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('channel_url', models.URLField(help_text="YouTube kanal URL: @handle, /channel/UC..., /c/name, /user/name. Aniq bo'lim uchun /videos yoki /shorts qo'shishingiz mumkin — aks holda kanalning eng yangi videolari olinadi.", max_length=500, verbose_name='Kanal havolasi')),
                ('count', models.PositiveSmallIntegerField(default=5, help_text="Kanalning eng yangi N ta videosidan tanlab olinadi. Bazada allaqachon mavjud videolar tashlab, keyingi eski videolarga o'tiladi — jami N ta YANGI kontent qo'shiladi.", verbose_name='Video soni (N)')),
                ('target_kind', models.CharField(choices=[('short', 'Shorts (Short.content_type=short)'), ('news', 'Yangiliklar (Short.content_type=news)'), ('cartoon', 'Multfilmlar (Short.content_type=cartoon)'), ('movie', 'Filmlar (Short.content_type=movie)'), ('dict:random_video', 'Diktant: Tasodifiy videolar'), ('dict:news', 'Diktant: Yangiliklar (video)'), ('dict:ted', 'Diktant: TED'), ('dict:ielts', 'Diktant: IELTS Listening'), ('dict:toefl', 'Diktant: TOEFL Listening'), ('dict:toeic', 'Diktant: TOEIC Listening'), ('dict:kids_story', 'Diktant: Bolalar hikoyalari')], default='short', help_text="Har video shu bo'limga qo'shiladi va AI pipeline o'zi ishga tushadi.", max_length=32, verbose_name="Qo'yiladigan bo'lim")),
                ('status', models.CharField(choices=[('pending', 'Kutayapti'), ('running', 'Ishlanmoqda'), ('done', 'Tayyor'), ('partial', 'Qisman (katalog tugadi)'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10, verbose_name='Holat')),
                ('error', models.TextField(blank=True, default='', verbose_name='Xato matni')),
                ('videos_created', models.JSONField(blank=True, default=list, help_text="[{'youtube_id': '...', 'title': '...', 'target_id': 42}, ...]", verbose_name='Yaratilgan videolar')),
                ('videos_skipped', models.JSONField(blank=True, default=list, help_text="Allaqachon bazada mavjud bo'lganlar.", verbose_name='Tashlab yuborilgan videolar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlandi')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugadi')),
            ],
            options={
                'verbose_name': 'Kanal ingest task',
                'verbose_name_plural': 'Kanal ingest tasklar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='catalog_cha_status_98195a_idx')],
            },
        ),
    ]
