# Generated by Django 5.0.9 on 2026-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_aijob_kind_alter_aijob_step_channelingesttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelingesttask',
            name='channel_url',
            field=models.URLField(help_text='Masalan: https://www.youtube.com/@WhiteHouse/videos yoki https://www.youtube.com/@WhiteHouse/shorts', max_length=500, verbose_name='Kanal URL'),
        ),
        migrations.AlterField(
            model_name='channelingesttask',
            name='count',
            field=models.PositiveSmallIntegerField(default=10, help_text="Kanalning eng yangi N ta YANGI videosini oladi. Bazada allaqachon bo'lganlar tashlab yuboriladi (count'ga hisoblanmaydi) — eski videolarga o'tib N tani to'ldiradi.", verbose_name='Video soni (N)'),
        ),
        migrations.AlterField(
            model_name='channelingesttask',
            name='target_kind',
            field=models.CharField(choices=[('shorts', 'Shorts'), ('movies', 'Filmlar'), ('cartoons', 'Multfilmlar'), ('news', 'Yangiliklar'), ('random_videos', 'Tasodifiy videolar')], default='shorts', help_text="Videolar shu bo'limga qo'shiladi. Shorts uchun URL ga /shorts qo'shing, oddiy videolar uchun /videos.", max_length=16, verbose_name="Qaysi bo'limga qo'yiladi"),
        ),
    ]
