# Generated by Django 5.0.9 on 2026-08-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_channelingesttask_channel_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name="Dislike'lar"),
        ),
        migrations.AddField(
            model_name='dictation',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name="Like'lar"),
        ),
        migrations.CreateModel(
            name='DictationReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=8, verbose_name='Reaksiya')),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_by_user', to='catalog.dictation', verbose_name='Diktant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Diktant reaksiyasi',
                'verbose_name_plural': 'Diktant reaksiyalari',
                'unique_together': {('user', 'dictation')},
            },
        ),
        migrations.CreateModel(
            name='ShortReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=8, verbose_name='Reaksiya')),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_by_user', to='catalog.short', verbose_name='Short')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Short reaksiyasi',
                'verbose_name_plural': 'Short reaksiyalari',
                'unique_together': {('user', 'short')},
            },
        ),
    ]
