# Generated by Django 5.0.9 on 2026-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_dictation_dislikes_dictation_likes_dictationreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='kind',
            field=models.CharField(choices=[('short', 'Short'), ('dictation', 'Dictation'), ('channel', 'Kanal ingest'), ('ielts', 'IELTS Listening test')], db_index=True, max_length=12, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='step',
            field=models.CharField(choices=[('whisper', 'Whisper (transkript)'), ('haiku', 'Haiku (savollar)'), ('ingest', "Kanaldan yig'ish"), ('parse', 'Parser (HTML)')], max_length=10, verbose_name='Bosqich'),
        ),
        migrations.CreateModel(
            name='IeltsListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('source_url', models.URLField(help_text='Masalan: https://engnovate.com/... — parser shu sahifadan test HTML sini olib chiqadi (audio havolalari bilan).', max_length=500, unique=True, verbose_name='Manba URL')),
                ('title', models.CharField(blank=True, default='', help_text="Parser sahifa <title> dan oladi. Qo'lda tahrirlash mumkin.", max_length=250, verbose_name='Sarlavha (avto)')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('html', models.TextField(blank=True, default='', help_text="Parser tayyorlagan to'liq sahifa (audio + savollar). Sayt iframe srcdoc ichida ko'rsatadi.", verbose_name='Standalone HTML (parser natijasi)')),
                ('total_questions', models.PositiveSmallIntegerField(default=40, help_text='Parser aniqlaydi. Standart IELTS Listening — 40 ta.', verbose_name='Savollar soni')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Har savol uchun ro\'yxat, masalan: {"1": ["Monday", "monday"], "2": ["blue"], ...}. Ro\'yxatdagi biror element foydalanuvchi javobiga to\'g\'ri kelsa — savol to\'g\'ri hisoblanadi (case-insensitive).', verbose_name="To'g'ri javoblar (1..N)")),
                ('status', models.CharField(choices=[('pending', 'Kutayapti (parser)'), ('parsing', 'Parse qilinmoqda'), ('parsed', 'Parse qilindi (javob kutilmoqda)'), ('ready', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10, verbose_name='Holat')),
                ('parse_error', models.TextField(blank=True, default='', verbose_name='Parser xatosi')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Chop etilgan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
            ],
            options={
                'verbose_name': 'IELTS Listening test',
                'verbose_name_plural': 'IELTS Listening testlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='catalog_iel_is_publ_6c5462_idx'), models.Index(fields=['status'], name='catalog_iel_status_be2edd_idx')],
            },
        ),
    ]
