# Generated by Django 5.0.9 on 2026-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_aijob_kind_alter_aijob_step_ieltslisteningtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonVideo',
            fields=[
            ],
            options={
                'verbose_name': '4. Multfilm',
                'verbose_name_plural': '4. Multfilmlar',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.short',),
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
            ],
            options={
                'verbose_name': '3. Film / uzun video',
                'verbose_name_plural': '3. Filmlar',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.short',),
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
            ],
            options={
                'verbose_name': '2. Yangilik (video)',
                'verbose_name_plural': '2. News videolar',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.short',),
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
            ],
            options={
                'verbose_name': '1. Shorts',
                'verbose_name_plural': '1. Shorts (qisqa video)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.short',),
        ),
        migrations.AlterModelOptions(
            name='short',
            options={'ordering': ['-created_at'], 'verbose_name': '5. Umumiy video (barchasi)', 'verbose_name_plural': '5. Umumiy videolar (barchasi)'},
        ),
        migrations.AlterField(
            model_name='ieltslisteningtest',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Parser sahifa &lt;title&gt; tegidan oladi. Qo'lda tahrirlash mumkin.", max_length=250, verbose_name='Sarlavha (avto)'),
        ),
    ]
