# Generated by Django 5.0.9 on 2026-09-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_cartoonvideo_movievideo_newsvideo_shortvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllYoutubeVideo',
            fields=[
            ],
            options={
                'verbose_name': 'Umumiy YouTube video',
                'verbose_name_plural': '6. Umumiy videolar (Short + Diktant)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.short',),
        ),
        migrations.AlterModelOptions(
            name='short',
            options={'ordering': ['-created_at'], 'verbose_name': '5. Shorts (barcha turlari)', 'verbose_name_plural': '5. Shorts — barchasi (tur almashtirish)'},
        ),
    ]
