# Generated by Django 5.0.9 on 2026-09-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_allyoutubevideo_alter_short_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsListeningTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Ball')),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='Jami savol')),
                ('results_json', models.JSONField(blank=True, default=dict, help_text='{"1": true, "2": false, ...}', verbose_name='Savol natijalari')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='catalog.ieltslisteningtest', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'IELTS natija',
                'verbose_name_plural': 'IELTS natijalar',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'test'], name='catalog_iel_user_id_964b90_idx')],
                'unique_together': {('user', 'test')},
            },
        ),
    ]
