# Generated by Django 5.0.9 on 2026-09-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_ieltslisteningtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltslisteningtest',
            name='parts_json',
            field=models.JSONField(blank=True, default=list, help_text="Parser ajratib olgan partlar: audio havolasi, savollar HTML'i va savol raqamlari. HTML shundan yasaladi — shu bois plyer yaxshilanganda manba saytga QAYTA MUROJAAT QILMASDAN sahifani qayta yasash mumkin (`manage.py rebuild_ielts_html`).", verbose_name='Partlar (xom)'),
        ),
    ]
