# Generated by Django 5.0.9 on 2026-09-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_short_is_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonDictation',
            fields=[
            ],
            options={
                'verbose_name': '11. Multfilm (video)',
                'verbose_name_plural': '11. Multfilmlar (video)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.CreateModel(
            name='MovieDictation',
            fields=[
            ],
            options={
                'verbose_name': '10. Film (video)',
                'verbose_name_plural': '10. Filmlar (video)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.dictation',),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='type',
            field=models.CharField(choices=[('short_story', 'Short Stories'), ('conversation', 'Suhbatlar'), ('number', 'Raqamlar'), ('spelling', 'Ismlarni harflab yozish'), ('ielts', 'IELTS Listening'), ('toefl', 'TOEFL Listening'), ('toeic', 'TOEIC Listening'), ('news', 'Yangiliklar'), ('random_video', 'Tasodifiy videolar'), ('movie', 'Filmlar'), ('cartoon', 'Multfilmlar'), ('ted', 'TED'), ('kids_story', 'Bolalar uchun hikoyalar')], db_index=True, help_text="Sayt navigatsiyasida shu bo'yicha guruhlanadi.", max_length=20, verbose_name='Mavzu'),
        ),
    ]
