# Generated by Django 5.0.9 on 2026-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_cartoondictation_moviedictation_alter_dictation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartoonVideo',
        ),
        migrations.DeleteModel(
            name='MovieVideo',
        ),
        migrations.DeleteModel(
            name='NewsVideo',
        ),
        migrations.AlterModelOptions(
            name='cartoondictation',
            options={'ordering': ['-created_at'], 'verbose_name': '11. Multfilm', 'verbose_name_plural': '11. Multfilmlar'},
        ),
        migrations.AlterModelOptions(
            name='moviedictation',
            options={'ordering': ['-created_at'], 'verbose_name': '10. Film', 'verbose_name_plural': '10. Filmlar'},
        ),
        migrations.AlterModelOptions(
            name='newsdictation',
            options={'ordering': ['-created_at'], 'verbose_name': '6. Yangilik', 'verbose_name_plural': '6. News videolar'},
        ),
    ]
